# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [9]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
np.__version__

'1.19.2'

In [10]:
hint(2)

hint: np.__version__, np.show_config)


In [4]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
   

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
nul_vec = np.zeros(10)
nul_vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
print(f'The memory size of nul_vec is {nul_vec.itemsize} bytes\n',
f'The dimensional size of nul_vec is {nul_vec.size}')

The memory size of nul_vec is 8 bytes
 The dimensional size of nul_vec is 10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
vec1 = np.zeros(10)
vec1[4] = 1
vec1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:
vec2 = np.arange(10,50)
vec2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [22]:
vec3 = np.arange(13,28)
print(vec3)
vec3 = vec3[::-1]
print(vec3)

[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]
[27 26 25 24 23 22 21 20 19 18 17 16 15 14 13]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [26]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


In [27]:
mtrx = np.arange(9).reshape(3,3)
mtrx

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [29]:
nz_idx = np.nonzero([1,2,0,0,4,0])
print(nz_idx)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [30]:
answer(11)

Z = np.eye(3)
print(Z)


In [31]:
z = np.eye(30) #диагональная матрица
z

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [33]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.07481443 0.31189707 0.70258447]
  [0.24724364 0.7277107  0.0477368 ]
  [0.3598048  0.59089164 0.00716997]]

 [[0.98783907 0.07674278 0.02077759]
  [0.87781474 0.90838748 0.0026367 ]
  [0.58342704 0.27867245 0.05553965]]

 [[0.03104925 0.70135543 0.92134877]
  [0.30132958 0.37571155 0.16133951]
  [0.50608561 0.52253285 0.5106433 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [39]:
rnd = np.random.random((10,10))
rnd
print(rnd.max(), rnd.min())

0.9990545409023479 0.00219675349856574


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [46]:
vec4 = np.random.random(30)
mean_vec4 = vec4.mean()
mean_vec4

0.5206529201554105

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [12]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
x = np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [23]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [25]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [29]:
x = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [31]:
x = np.random.random((5,5))
x = (x - np.mean (x)) / (np.std (x))
print(x)

[[ 1.03303028  1.23397081  0.28561518 -1.62555024  0.10363002]
 [-0.10285056  0.57427133 -0.14447599  0.84155433 -0.59857256]
 [ 0.83740035 -1.27890862 -1.22132995  1.27082666 -1.02352353]
 [-1.61548872  0.10542007  0.60689806  1.19385786  1.25518667]
 [-0.56363916 -1.50333903  1.22845053  0.35426415 -1.24669794]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [35]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [37]:
x = np.dot(np.ones((5,3)), np.ones((3,2)))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [39]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [41]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [48]:
Z = np.zeros(5)
print(Z**Z)
#2 << Z >> 2
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#Z<Z>Z

[1. 1. 1. 1. 1.]
[False False False False False]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[0. 0. 0. 0. 0.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [50]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-50-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-50-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [56]:
x = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(x)), x))

[ 2.  3. -8.  4. -4.  4. -6.  8. -7. -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [58]:
x1 = np.random.randint(0,10,10)
x2 = np.random.randint(0,10,10)
print(np.intersect1d(x1,x2))

[1 5 6 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [61]:
defaults = np.seterr(all="ignore")
x = np.ones(1) / 0
_ = np.seterr(**defaults)  # вернул все обратно

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [63]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-63-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [66]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [68]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [70]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [72]:
x = np.random.uniform(0,10,10)

print(x - x%1)
print(x // 1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))

[3. 6. 6. 8. 2. 0. 4. 5. 2. 7.]
[3. 6. 6. 8. 2. 0. 4. 5. 2. 7.]
[3. 6. 6. 8. 2. 0. 4. 5. 2. 7.]
[3 6 6 8 2 0 4 5 2 7]
[3. 6. 6. 8. 2. 0. 4. 5. 2. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [74]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [79]:
def generate():
    for i in range(10):
        yield i
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [81]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [83]:
x = np.random.random(10)
x.sort()
print(x)

[0.07952862 0.11828238 0.13428238 0.22017426 0.23063603 0.34631785
 0.57974496 0.67329456 0.74158584 0.88240068]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [85]:
x = np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [87]:
x = np.random.randint(0,2,5)
y = np.random.randint(0,2,5)
equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [91]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [93]:
x = np.random.random((10,2))
a,b = x[:,0], x[:,1]
r = np.sqrt(a**2+b**2)
t = np.arctan2(b,a)
print(r)
print(t)

[1.40935924 0.37041862 0.18840534 1.10353351 0.52236356 1.26460073
 0.85533563 1.21515119 0.77132331 0.46440313]
[0.78650296 0.05119127 0.77474032 1.10091168 0.59188499 0.7953326
 0.68757979 0.70083546 0.36477557 1.19996098]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [95]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.70873668 0.41370369 0.307592   0.24545561 0.50023457 0.
 0.85844388 0.31777644 0.68441562 0.42969525]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [97]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [99]:
x = np.arange(8)
y = x + 0.5
a = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(a))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [101]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [103]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((40,40))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [105]:
x = np.arange(100)
a = np.random.uniform(0,100)
index = (np.abs(x-a)).argmin()
print(x[index])

92


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [107]:
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-107-1c50e4e32ac3>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [109]:
x = np.random.random((10,2))
a,b = np.atleast_2d(x[:,0], x[:,1])
c = np.sqrt( (a-a.T)**2 + (b-b.T)**2)
print(c)

[[0.         0.76862724 0.5454019  0.5604284  0.88299373 0.29068277
  0.71523432 0.26175809 0.74467629 0.83758972]
 [0.76862724 0.         0.83045918 0.28152263 0.74486725 0.90680435
  0.76584991 0.50989115 0.09119104 1.20632295]
 [0.5454019  0.83045918 0.         0.55054512 0.43825676 0.34023673
  0.23008794 0.51444267 0.86748788 0.38193781]
 [0.5604284  0.28152263 0.55054512 0.         0.54573126 0.64295841
  0.51278486 0.30535339 0.31911351 0.92918104]
 [0.88299373 0.74486725 0.43825676 0.54573126 0.         0.76037194
  0.20865965 0.72592887 0.81938514 0.64869873]
 [0.29068277 0.90680435 0.34023673 0.64295841 0.76037194 0.
  0.55987722 0.43008233 0.90992986 0.5564559 ]
 [0.71523432 0.76584991 0.23008794 0.51278486 0.20865965 0.55987722
  0.         0.6041256  0.82398958 0.4843644 ]
 [0.26175809 0.50989115 0.51444267 0.30535339 0.72592887 0.43008233
  0.6041256  0.         0.49435452 0.8783311 ]
 [0.74467629 0.09119104 0.86748788 0.31911351 0.81938514 0.90992986
  0.82398958 0.49435

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [111]:
x = (np.random.rand(10)*100).astype(np.float32)
y = x.view(np.int32)
y[:] = x
print(y)

[11 38 94  6 92 70 27 53 57 19]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [113]:
from io import StringIO
x = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
a = np.genfromtxt(x, delimiter=",", dtype=np.int)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [115]:
x = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [117]:
a, b = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
x = np.sqrt(a*a+b*b)
sigma, mu = 1.0, 0.0
y = np.exp(-( (x-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(y)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [119]:
x = 10
y = 3
a = np.zeros((x,x))
np.put(a, np.random.choice(range(x*x), y, replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [121]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[ 0.32068078 -0.16054783  0.08528555  0.19965859  0.01288293 -0.34229663
   0.29668763  0.12986002 -0.18802809 -0.35418295]
 [ 0.29582554 -0.26314761  0.33538199  0.1681609   0.27664976  0.08633332
  -0.18934636 -0.35623487  0.18193026 -0.53555294]
 [ 0.61821218 -0.27482833  0.14165257 -0.10166524 -0.26936762 -0.18775682
   0.38450312 -0.22138806 -0.01972528 -0.06963652]
 [-0.2731132  -0.4460177   0.36626633  0.2942247  -0.275208   -0.38154459
   0.39483593  0.4142775  -0.45944204  0.36572107]
 [-0.07918227  0.53265385 -0.35355039 -0.05827504  0.52638754 -0.34656632
   0.4771965   0.07743248 -0.35283995 -0.42325642]]


#### 59. How to sort an array by the nth column? (★★☆)

In [123]:
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[3 6 0]
 [8 5 2]
 [8 9 3]]
[[8 5 2]
 [3 6 0]
 [8 9 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [126]:
x=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(x).all(axis=0))

[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [128]:
x = np.random.uniform(0,1,10)
y = 0.5
a = x.flat[np.abs(x - y).argmin()]
print(a)

0.5433168113369151


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [130]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [132]:
class MyArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

x = MyArray(np.arange(10), "range_10")
print (x.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [134]:
x = np.ones(10)
y = np.random.randint(0,len(x),20)
x += np.bincount(y, minlength=len(x))
print(x)

[3. 3. 3. 5. 1. 2. 1. 4. 4. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [136]:
x = [4,6,9,8,3,2]
y = [9,1,2,3,1,8]
a = np.bincount(y,x)
print(a)

[0. 9. 9. 8. 0. 0. 0. 0. 2. 4.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [138]:
a, b = 256, 256
x = np.random.randint(0, 4, (b, a, 3)).astype(np.ubyte)
colors = np.unique(x.reshape(-1, 3), axis=0)
y = len(colors)
print(y)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [140]:
x = np.random.randint(0,10,(3,4,3,4))
sum = x.sum(axis=(-2,-1))
print(sum)

[[71 45 46 54]
 [45 41 56 57]
 [71 52 44 62]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [142]:
x = np.random.uniform(0,1,100)
y = np.random.randint(0,10,100)
x_sum = np.bincount(y, weights=x)
x_count = np.bincount(y)
x_mean = x_sum / x_count
print(x_mean)

[0.39032141 0.5179688  0.56076077 0.48383809 0.52026026 0.60856665
 0.53632153 0.36633823 0.40718062 0.49918237]


#### 69. How to get the diagonal of a dot product? (★★★)

In [144]:
x = np.random.uniform(0,1,(5,5))
y = np.random.uniform(0,1,(5,5))
np.sum(x * y.T, axis=1)

array([0.6521908 , 0.9414057 , 0.90389993, 1.3437076 , 0.48375568])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [146]:
x = np.array([1,2,3,4,5])
a = 3
y = np.zeros(len(x) + (len(x)-1)*(a))
y[::a+1] = x
print(y)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [148]:
x = np.ones((5,5,3))
y = 2*np.ones((5,5))
print(x * y[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [150]:
x = np.arange(25).reshape(5,5)
x[[0,1]] = x[[1,0]]
print(x)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [153]:
faces = np.random.randint(0,100,(10,3))
x = np.roll(faces.repeat(2,axis=1),-1,axis=1)
x = x.reshape(len(x)*3,2)
x = np.sort(x,axis=1)
y = x.view( dtype=[('p0',x.dtype),('p1',x.dtype)] )
y = np.unique(y)
print(y)

[( 1, 27) ( 1, 64) ( 6, 26) ( 6, 38) ( 7, 31) ( 7, 95) ( 8, 69) ( 8, 90)
 (14, 20) (14, 89) (20, 89) (22, 27) (22, 47) (26, 38) (27, 47) (27, 64)
 (31, 95) (32, 49) (32, 52) (36, 39) (36, 53) (37, 60) (37, 82) (39, 53)
 (48, 58) (48, 90) (49, 52) (58, 90) (60, 82) (69, 90)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [155]:
x = np.bincount([1,1,2,3,4,4,6])
y = np.repeat(np.arange(len(x)), x)
print(y)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [157]:
def moving_average(x, n=3) :
    ret = np.cumsum(x, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = np.arange(20)
print(moving_average(a, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [165]:
from numpy.lib import stride_tricks

def rolling(x, window):
    shape = (x.size - window + 1, window)
    strides = (x.strides[0], x.strides[0])
    return stride_tricks.as_strided(x, shape=shape, strides=strides)
y = rolling(np.arange(10), 3)
print(y)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [167]:
x = np.random.randint(0,2,100)
np.logical_not(x, out=x)

array([1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [169]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[4.05611657 4.80088255 7.43558694 2.35486356 3.5798026  9.6778496
 4.93318622 1.17296561 1.76731444 1.05030564]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [171]:
a = np.random.uniform(-10, 10, (10,2))
b = np.random.uniform(-10,10,(10,2))
x = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(a,b,x_i) for x_i in x]))

[[8.28274714e+00 1.46249091e+01 3.05996621e+00 8.89902421e+00
  2.24757262e+00 6.37389465e+00 1.61742237e+01 3.17809379e-03
  3.61697062e+00 5.22257177e+00]
 [2.14370197e+00 2.19446624e+00 9.09225876e+00 3.03128005e+00
  1.39947201e+01 1.18374423e+00 5.09414901e+00 1.17980169e+01
  8.11507664e+00 3.02968199e+00]
 [2.29510706e+00 1.12333834e+01 1.12938508e+00 8.44929907e+00
  2.36387244e+00 9.61358325e-01 1.06548225e+01 4.77455144e+00
  3.52634273e+00 1.15142290e+01]
 [7.45577902e+00 1.60544085e+01 3.89423203e+00 1.20794253e+01
  1.09448863e+00 3.15506597e+00 1.58392258e+01 3.51939700e-01
  6.97118847e+00 9.91625618e+00]
 [6.36289945e+00 1.79535181e+00 1.32353643e+01 6.08168022e+00
  1.69076331e+01 2.12557085e+00 8.44674067e-01 1.60150798e+01
  1.10171591e+01 4.23878731e+00]
 [8.63638663e+00 1.59269901e+00 1.13452267e+01 1.73600025e+00
  8.67852904e+00 1.03449234e+01 1.98302534e-01 1.53283502e+01
  2.75709299e+00 1.60505234e+01]
 [8.39450960e-01 1.14016939e+01 1.40876751e+00 1.00361719e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [174]:
x = np.arange(1,15,dtype=np.uint32)
y = stride_tricks.as_strided(x,(11,4),(4,4))
print(y)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [176]:
x = np.random.uniform(0,1,(10,10))
a, b, c = np.linalg.svd(x) # Singular Value Decomposition
rank = np.sum(b > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [178]:
x = np.random.randint(0,10,50)
print(np.bincount(x).argmax())

9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [180]:
x = np.random.randint(0,5,(10,10))
a = 3
i = 1 + (x.shape[0]-3)
j = 1 + (x.shape[1]-3)
y = stride_tricks.as_strided(x, shape=(i, j, a, a), strides=x.strides + x.strides)
print(y)

[[[[1 1 3]
   [1 3 2]
   [0 2 3]]

  [[1 3 2]
   [3 2 1]
   [2 3 4]]

  [[3 2 0]
   [2 1 4]
   [3 4 3]]

  [[2 0 2]
   [1 4 0]
   [4 3 3]]

  [[0 2 2]
   [4 0 2]
   [3 3 1]]

  [[2 2 2]
   [0 2 0]
   [3 1 2]]

  [[2 2 0]
   [2 0 0]
   [1 2 2]]

  [[2 0 0]
   [0 0 1]
   [2 2 4]]]


 [[[1 3 2]
   [0 2 3]
   [3 1 0]]

  [[3 2 1]
   [2 3 4]
   [1 0 4]]

  [[2 1 4]
   [3 4 3]
   [0 4 4]]

  [[1 4 0]
   [4 3 3]
   [4 4 2]]

  [[4 0 2]
   [3 3 1]
   [4 2 3]]

  [[0 2 0]
   [3 1 2]
   [2 3 1]]

  [[2 0 0]
   [1 2 2]
   [3 1 3]]

  [[0 0 1]
   [2 2 4]
   [1 3 4]]]


 [[[0 2 3]
   [3 1 0]
   [0 0 1]]

  [[2 3 4]
   [1 0 4]
   [0 1 4]]

  [[3 4 3]
   [0 4 4]
   [1 4 0]]

  [[4 3 3]
   [4 4 2]
   [4 0 3]]

  [[3 3 1]
   [4 2 3]
   [0 3 3]]

  [[3 1 2]
   [2 3 1]
   [3 3 1]]

  [[1 2 2]
   [3 1 3]
   [3 1 2]]

  [[2 2 4]
   [1 3 4]
   [1 2 0]]]


 [[[3 1 0]
   [0 0 1]
   [1 0 3]]

  [[1 0 4]
   [0 1 4]
   [0 3 4]]

  [[0 4 4]
   [1 4 0]
   [3 4 1]]

  [[4 4 2]
   [4 0 3]
   [4 1 3]]

  [[4 2 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [185]:
x, y = 10, 20
a = np.ones((x,y,y))
b = np.ones((x,y,1))
c = np.tensordot(a, b, axes=[[0, 2], [0, 1]])
print(c)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [193]:
x = np.ones((16,16))
a = 4
y = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], a), axis=0),
                                       np.arange(0, x.shape[1], a), axis=1)
print(y)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [196]:
x = np.arange(10000)
np.random.shuffle(x)
y = 5
print (x[np.argpartition(-x,y)[:y]])

[9999 9998 9995 9996 9997]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [202]:
x = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
y = np.core.records.fromarrays(x.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(y)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [204]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('y,y,y->y',x,x,x)

5.59 s ± 602 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
790 ms ± 273 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
390 ms ± 8.18 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [207]:
x = np.random.randint(0,5,(8,3))
y = np.random.randint(0,5,(2,2))

a = (x[..., np.newaxis, np.newaxis] == y)
rows = np.where(a.any((3,1)).all(1))[0]
print(rows)

[3 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [209]:
x = np.random.randint(0,5,(10,3))
print(x)
y = np.all(x[:,1:] == x[:,:-1], axis=1)
a = x[~y]
print(a)

[[1 0 1]
 [2 2 3]
 [3 2 2]
 [2 3 4]
 [4 1 0]
 [1 0 3]
 [2 2 3]
 [0 3 2]
 [3 0 4]
 [2 4 1]]
[[1 0 1]
 [2 2 3]
 [3 2 2]
 [2 3 4]
 [4 1 0]
 [1 0 3]
 [2 2 3]
 [0 3 2]
 [3 0 4]
 [2 4 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [211]:
x = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
y = ((x.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(y[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [214]:
x = np.random.randint(0,2,(6,3))
y = np.unique(x, axis=0)
print(y)

[[0 0 0]
 [0 1 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [216]:
x = np.random.uniform(0,1,10)
y = np.random.uniform(0,1,10)

np.einsum('i->', x)       
np.einsum('i,i->i', x, y) 
np.einsum('i,i', x, y)    
np.einsum('i,j->ij', x, y)   

array([[0.15040772, 0.32253214, 0.32737258, 0.31951628, 0.03994787,
        0.11022002, 0.26961115, 0.14894867, 0.18871066, 0.03689653],
       [0.03689072, 0.07910793, 0.08029515, 0.07836823, 0.00979807,
        0.02703383, 0.06612792, 0.03653286, 0.04628534, 0.00904967],
       [0.02800347, 0.06005024, 0.06095146, 0.05948874, 0.00743764,
        0.02052118, 0.05019722, 0.02773182, 0.03513486, 0.00686954],
       [0.14884347, 0.31917778, 0.32396788, 0.31619329, 0.03953241,
        0.10907373, 0.26680717, 0.14739959, 0.18674805, 0.03651281],
       [0.32670316, 0.7005775 , 0.7110915 , 0.69402671, 0.08677145,
        0.23941077, 0.58562693, 0.32353391, 0.40990161, 0.08014358],
       [0.28621609, 0.61375762, 0.62296866, 0.60801864, 0.07601819,
        0.20974152, 0.51305243, 0.2834396 , 0.35910407, 0.0702117 ],
       [0.08759265, 0.1878324 , 0.19065132, 0.18607606, 0.02326436,
        0.06418862, 0.15701291, 0.08674294, 0.10989905, 0.02148736],
       [0.15253338, 0.32709036, 0.3319992

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [219]:
x = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
a = 4
y = np.logical_and.reduce(np.mod(x, 1) == 0, axis=-1)
y &= (x.sum(axis=-1) == a)
print(x[y])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [221]:
x = np.random.randn(100) 
y = 1000 
idx = np.random.randint(0, x.size, (y, x.size))
means = x[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.31078164  0.04780972]
